#!/usr/bin/with-contenv bash

# Determine if the folder already exists is needed
if [ ! -d "/config_holder/$CONTAINER_NAME" ]; then
  echo "***** Creating a new configuration holder directory at /config_holder/$CONTAINER_NAME *****"

  mkdir -p "/config_holder/$CONTAINER_NAME"
  echo "(DEBUG) $?"

  if [ ! -L "/config_holder/$CONTAINER_NAME" ]; then
    echo "***** Creating symlink from /config to /config_holder/$CONTAINER_NAME/config *****"

    ln -s /config "/config_holder/$CONTAINER_NAME/config"
    echo "(DEBUG) $?"
  fi
fi
