#!/usr/bin/with-contenv bash

# Determine if the backup folder already exists, and create it if needed
if [ ! -d "/backup/$CONTAINER_NAME/" ]; then
  echo "***** Creating a new configuration holder directory at /backup/$CONTAINER_NAME/ *****"
  mkdir -p "/backup/$CONTAINER_NAME/"
fi

# Update apt as needed and install rsync
if [ -f /usr/bin/apt ]; then
    apt update
fi

if ! command -v git; then
    # Ubuntu
    if [ -f /usr/bin/apt ]; then
        apt install --no-install-recommends -y rsync
        apt autoremove
        apt clean
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        apk add --no-cache rsync
    fi
fi